language: python
python:
  - "3.7"
install:
  - cp contrib/env-sample .env
  - pip install -q -r requirements.txt
  - pip install codecov
script:
  - python manage.py test
  - coverage run eventex/subscriptions/tests.py