# Generated by Django 2.2.6 on 2019-12-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField()),
                ('photo', models.URLField(verbose_name='Foto')),
                ('website', models.URLField(verbose_name='Site')),
                ('description', models.TextField(verbose_name='Sobre mim')),
            ],
        ),
    ]
