# Generated by Django 2.2.6 on 2019-12-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191216_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário'),
        ),
    ]
