# Generated by Django 2.2.6 on 2019-12-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_course_abc_to_mti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOld',
        ),
    ]
